name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .
    - name: Test with pytest
      run: |
        pytest
    - name: Run pylint
      run: |
        pylint dr_app/predict.py
        pylint dr_app/streamlit_app.py
        pylint model_training/train_diagnosis.py
        pylint model_training/train_imquality.py
        pylint model_training/model_summary.py